2021-03-26T08:24:30.306367+00:00 app[worker.1]: Ignoring exception in on_command_error
2021-03-26T08:24:30.311384+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-26T08:24:30.311509+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 85, in wrapped
2021-03-26T08:24:30.311510+00:00 app[worker.1]:     ret = await coro(*args, **kwargs)
2021-03-26T08:24:30.311552+00:00 app[worker.1]:   File "/app/cogs/music.py", line 376, in _now
2021-03-26T08:24:30.311554+00:00 app[worker.1]:     await ctx.send(embed=await ctx.voice_state.current.create_embed())
2021-03-26T08:24:30.311595+00:00 app[worker.1]:   File "/app/cogs/music.py", line 156, in create_embed
2021-03-26T08:24:30.311612+00:00 app[worker.1]:     await self.client.change_presence(activity=discord.Game(name="{0.source.title}".format(self)))
2021-03-26T08:24:30.311690+00:00 app[worker.1]: AttributeError: 'Song' object has no attribute 'client'
2021-03-26T08:24:30.311731+00:00 app[worker.1]: 
2021-03-26T08:24:30.311732+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-03-26T08:24:30.311733+00:00 app[worker.1]: 
2021-03-26T08:24:30.311769+00:00 app[worker.1]: Traceback (most recent call last):
2021-03-26T08:24:30.312056+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
2021-03-26T08:24:30.312057+00:00 app[worker.1]:     await coro(*args, **kwargs)
2021-03-26T08:24:30.312097+00:00 app[worker.1]:   File "main.py", line 85, in on_command_error
2021-03-26T08:24:30.312098+00:00 app[worker.1]:     raise error
2021-03-26T08:24:30.312173+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 902, in invoke
2021-03-26T08:24:30.312174+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2021-03-26T08:24:30.312212+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 864, in invoke
2021-03-26T08:24:30.312213+00:00 app[worker.1]:     await injected(*ctx.args, **ctx.kwargs)
2021-03-26T08:24:30.312252+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 94, in wrapped
2021-03-26T08:24:30.312253+00:00 app[worker.1]:     raise CommandInvokeError(exc) from exc
2021-03-26T08:24:30.312344+00:00 app[worker.1]: discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Song' object has no attribute 'client'
